name 'jboss'
maintainer 'Aliaksandr_Karavai'
maintainer_email 'aliaksandr_karavai@epam.com'
license 'all_rights'
description 'Installs/Configures jboss'
long_description 'Installs/Configures jboss'
version '0.1.0'
#depends 'java'
